# This workflow is executed on push of every commit on the development branch
# This is a basic workflow that is used to check the validity of code by running pre-definded tests

name: Basic Workflow
# This workflow runs whenever someone pushes to the master branch with the tag 'test'
on: 
  push: 
    branches:
      - development
jobs:
  build:
    name: Build debug apk
    runs-on: ubuntu-latest
    # The enviourment uses the latest java version and the latest flutter version
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.7.8+hotfix.4'
    - run: pwd > test.txt
    # Upgrade flutter version if possible
    - run: flutter upgrade
    # Make sure to download all dependencies in the enviourment before building
    - run: flutter pub get
    # Running all unit tests written to ensure there are no errors
    - run: flutter test